anHsudo: required
dist: trusty
language: node_js
node_js:
  - "6"
before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update -qq
  - sudo apt-get install -qq wine fakeroot
install: npm install
before_deploy:
deploy:
  provider: releases
  api-key:
    secure: Nb4qJlmLEE2/ETHEYe8V8eGI08d4GuE5kdQef5ZnB4PrstppLlAjShv5E4DNTsyalMOMDjpw9v+9aQNzxGiGv+lCVVL5oFvqvDpcYusRuF9Qua7oJtFh+5FvjgC1DDjauk5Z7WQWMvzWwfNmqbY/lxPbA4zVy4kdYkGV/8WnzA9AL5fU0ZU8gDsFjcr9Pz81XDsDXtPH/+iMuclMsEl8V/ZuswWlZaFn1Jnb1tcGC5WUCsuNQo/+gGfSK6Qcf9AKsIrOjdzi55s4jqH1N7P/kKi4a2tWUTwmSLrOxdUmSYjXVOxMu0cAEnHSeYREv/5o6J0MbfQrDoxh2y5roPZzqE+FAuFLl+b/+bYlW0mrfYfSuP/VX9LYh5JSvrhN7rZuUfMqS1iM7c9Dx8sZadMnvYEAAJhH8IV/9SkuRa/8QoIpXf7YB9v1jERxs4gk5CPT5Aml6nY/CvMWiEQ/wJhC7iZd/QRHshgfNLfAGlbbNU2KP6ZsVAGD601fyST/8neoQqLqS9mteOr1QME3c5EFw+XaauIQNYZSl+wJr8Y1YMcKY+fbJqqR0TXkbsoxFgV9PRf/4ZCjIJYtmelQVlM7j20XavOHM/Ko6/y7a3pohFz+ql3YR9jGF5XW2foXb4+e6DwTGL91/f75hYcsvXxoKbeaBjWpaSK8532UTeVkhPM=
  file_glob: true
  file: dist/packages/*
  skip_cleanup: true
  on:
    tags: true
before_deploy:
  - export VERSION=$(sed -nE 's/^\s*"version":\ "(.*?)",$/\1/p' package.json)
  - npm run build
  - npm run deb32
  - npm run deb64
  - npm run debarm
  - cd dist
  - mkdir packages
  - mv open-stage-control-linux-ia32/*.deb packages/open-stage-control-${VERSION}-i386.deb
  - mv open-stage-control-linux-x64/*.deb packages/open-stage-control-${VERSION}-amd64.deb
  - mv open-stage-control-linux-armv7l/*.deb packages/open-stage-control-${VERSION}-armv7l.deb
  - mv open-stage-control-win32-ia32   open-stage-control-${VERSION}-win32-ia32
  - mv open-stage-control-win32-x64    open-stage-control-${VERSION}-win32-x64
  - mv open-stage-control-linux-ia32   open-stage-control-${VERSION}-linux-ia32
  - mv open-stage-control-linux-x64    open-stage-control-${VERSION}-linux-x64
  - mv open-stage-control-linux-armv7l open-stage-control-${VERSION}-linux-armv7l
  - mv open-stage-control-linux-arm64 open-stage-control-${VERSION}-linux-arm64
  - zip -q -r --symlinks packages/open-stage-control-${VERSION}-osx.zip open-stage-control-darwin-x64/open-stage-control.app
  - zip -q -r packages/open-stage-control-${VERSION}-win32-ia32.zip     open-stage-control-${VERSION}-win32-ia32
  - zip -q -r packages/open-stage-control-${VERSION}-win32-x64.zip      open-stage-control-${VERSION}-win32-x64
  - zip -q -r packages/open-stage-control-${VERSION}-linux-ia32.zip     open-stage-control-${VERSION}-linux-ia32
  - zip -q -r packages/open-stage-control-${VERSION}-linux-x64.zip      open-stage-control-${VERSION}-linux-x64
  - zip -q -r packages/open-stage-control-${VERSION}-linux-armv7l.zip   open-stage-control-${VERSION}-linux-armv7l
  - zip -q -r packages/open-stage-control-${VERSION}-linux-arm64.zip   open-stage-control-${VERSION}-linux-arm64
  - ls packages
  - cd ..
